export enum ActiveType {
    FACILITY_INSPECTION = 'FACILITY_INSPECTION',
    STUDENT_ATTENDANCE = 'STUDENT_ATTENDANCE',
    MORNING_ASSEMBLY = 'MORNING_ASSEMBLY',
    BREAK = 'BREAK',
    STUDENT_DISMISSAL = 'STUDENT_DISMISSAL',
    RECORD_ANALYSIS = 'RECORD_ANALYSIS',
    STUDENT_WORK_ANALYSIS = 'STUDENT_WORK_ANALYSIS',
    TEST_ANALYSIS = 'TEST_ANALYSIS',
    OTHER = 'OTHER'
}
