export enum Permission {
    PERM1 = "PERM1",

    // Dashboard Permissions
    CHEQA_REVIEWER_DASHBOARD_COUNTS_RATIOS = "CHEQA_REVIEWER_DASHBOARD_COUNTS_RATIOS",
    CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_STATUS = "CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_STATUS",
    CHEQA_REVIEWER_DASHBOARD_YEAR_COMPARISON = "CHEQA_REVIEWER_DASHBOARD_YEAR_COMPARISON",
    CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_SPECIALIZATION = "CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_SPECIALIZATION",
    CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_COUNTRY = "CHEQA_REVIEWER_DASHBOARD_DISTRIBUTION_BY_COUNTRY",
    CHEQA_REVIEWER_DASHBOARD_ACTIVITIES_PARTICIPATION = "CHEQA_REVIEWER_DASHBOARD_ACTIVITIES_PARTICIPATION",
    CHEQA_REVIEWER_DASHBOARD_JOIN_REQUESTS_BY_STATUS = "CHEQA_REVIEWER_DASHBOARD_JOIN_REQUESTS_BY_STATUS",
    CHEQA_REVIEWER_DASHBOARD_WITHDRAWAL_REQUESTS_BY_STATUS = "CHEQA_REVIEWER_DASHBOARD_WITHDRAWAL_REQUESTS_BY_STATUS",
    CHEQA_REVIEWER_DASHBOARD_CANDIDATES_REGISTER = "CHEQA_REVIEWER_DASHBOARD_CANDIDATES_REGISTER",
    CHEQA_REVIEWER_DASHBOARD_REVIEWERS_REGISTER = "CHEQA_REVIEWER_DASHBOARD_REVIEWERS_REGISTER",

    OQF_REVIEWER_DASHBOARD_COUNTS_RATIOS = "OQF_REVIEWER_DASHBOARD_COUNTS_RATIOS",
    OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_STATUS = "OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_STATUS",
    OQF_REVIEWER_DASHBOARD_YEAR_COMPARISON = "OQF_REVIEWER_DASHBOARD_YEAR_COMPARISON",
    OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_SPECIALIZATION = "OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_SPECIALIZATION",
    OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_COUNTRY = "OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_COUNTRY",
    OQF_REVIEWER_DASHBOARD_ACTIVITIES_PARTICIPATION = "OQF_REVIEWER_DASHBOARD_ACTIVITIES_PARTICIPATION",
    OQF_REVIEWER_DASHBOARD_JOIN_REQUESTS_BY_STATUS = "OQF_REVIEWER_DASHBOARD_JOIN_REQUESTS_BY_STATUS",
    OQF_REVIEWER_DASHBOARD_CANDIDATES_REGISTER = "OQF_REVIEWER_DASHBOARD_CANDIDATES_REGISTER",
    OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_EMPLOYER = "OQF_REVIEWER_DASHBOARD_DISTRIBUTION_BY_EMPLOYER",
    OQF_REVIEWER_DASHBOARD_REVIEWERS_REGISTER = "OQF_REVIEWER_DASHBOARD_REVIEWERS_REGISTER",

    // SERVICE MANAGEMENT
    VIEW_SERVICE = "VIEW_SERVICE",
    EDIT_SERVICE = "EDIT_SERVICE",
    MANAGE_SERVICE = "MANAGE_SERVICE",

    // CHEQA External Reviewer Acceptance Criteria
    CHEQA_ER_Acceptance_CRITERIA_VIEW = "CHEQA_ER_Acceptance_CRITERIA_VIEW",
    CHEQA_ER_Acceptance_CRITERIA_MANAGE = "CHEQA_ER_Acceptance_CRITERIA_MANAGE",
    CHEQA_ER_Acceptance_CRITERIA_ADD = "CHEQA_ER_Acceptance_CRITERIA_ADD",
    CHEQA_ER_Acceptance_CRITERIA_UPDATE = "CHEQA_ER_Acceptance_CRITERIA_UPDATE",
    CHEQA_ER_Acceptance_CRITERIA_DELETE = "CHEQA_ER_Acceptance_CRITERIA_DELETE",

    // CSEQA External Reviewer Acceptance Criteria
    CSEQA_ER_Acceptance_CRITERIA_VIEW = "CSEQA_ER_Acceptance_CRITERIA_VIEW",
    CSEQA_ER_Acceptance_CRITERIA_MANAGE = "CSEQA_ER_Acceptance_CRITERIA_MANAGE",
    CSEQA_ER_Acceptance_CRITERIA_ADD = "CSEQA_ER_Acceptance_CRITERIA_ADD",
    CSEQA_ER_Acceptance_CRITERIA_UPDATE = "CSEQA_ER_Acceptance_CRITERIA_UPDATE",
    CSEQA_ER_Acceptance_CRITERIA_DELETE = "CSEQA_ER_Acceptance_CRITERIA_DELETE",

    // OQF External Reviewer Acceptance Criteria
    OQF_ER_Acceptance_CRITERIA_VIEW = "OQF_ER_Acceptance_CRITERIA_VIEW",
    OQF_ER_Acceptance_CRITERIA_MANAGE = "OQF_ER_Acceptance_CRITERIA_MANAGE",
    OQF_ER_Acceptance_CRITERIA_ADD = "OQF_ER_Acceptance_CRITERIA_ADD",
    OQF_ER_Acceptance_CRITERIA_UPDATE = "OQF_ER_Acceptance_CRITERIA_UPDATE",
    OQF_ER_Acceptance_CRITERIA_DELETE = "OQF_ER_Acceptance_CRITERIA_DELETE",

    // External Reviewer Registration Settings
    CHEQA_ER_registration_settings_MANAGE = "CHEQA_ER_registration_settings_MANAGE",
    CHEQA_ER_registration_settings_VIEW = "CHEQA_ER_registration_settings_VIEW",
    CHEQA_ER_registration_settings_UPDATE = "CHEQA_ER_registration_settings_UPDATE",

    CSEQA_ER_registration_settings_MANAGE = "CSEQA_ER_registration_settings_MANAGE",
    CSEQA_ER_registration_settings_VIEW = "CSEQA_ER_registration_settings_VIEW",
    CSEQA_ER_registration_settings_UPDATE = "CSEQA_ER_registration_settings_UPDATE",

    CSEQA_ER_Interview_results_Registration_VIEW = "CSEQA_ER_Interview_results_Registration_VIEW",
    CSEQA_ER_Training_results_Registration_Request_VIEW_ALL = "CSEQA_ER_Training_results_Registration_Request_VIEW_ALL",
    CSEQA_ER_Interview_results_Registration_SUBMIT = "CSEQA_ER_Interview_results_Registration_SUBMIT",

    OQF_ER_registration_settings_MANAGE = "OQF_ER_registration_settings_MANAGE",
    OQF_ER_registration_settings_VIEW = "OQF_ER_registration_settings_VIEW",
    OQF_ER_registration_settings_UPDATE = "OQF_ER_registration_settings_UPDATE",

    CHEQA_ER_Request_VIEW_ALL = "CHEQA_ER_Request_VIEW_ALL",
    CSEQA_ER_Request_VIEW_ALL = "CSEQA_ER_Request_VIEW_ALL",
    OQF_ER_Request_VIEW_ALL = "OQF_ER_Request_VIEW_ALL",

    CHEQA_ER_VIEW = "CHEQA_ER_VIEW",
    CSEQA_ER_VIEW = "CSEQA_ER_VIEW",
    OQF_ER_VIEW = "OQF_ER_VIEW",


    CHEQA_External_reviewers_Request_COMPLETE_TASK = 'CHEQA_External_reviewers_Request_COMPLETE_TASK',
    CSEQA_External_reviewers_Request_COMPLETE_TASK = 'CSEQA_External_reviewers_Request_COMPLETE_TASK',
    OQF_External_reviewers_Request_COMPLETE_TASK = 'OQF_External_reviewers_Request_COMPLETE_TASK',

    // External Reviewer Registration request view all
    CSEQA_ER_Registration_Request_VIEW_ALL = "CSEQA_ER_Registration_Request_VIEW_ALL",
    CHEQA_ER_Registration_Request_VIEW_ALL = "CHEQA_ER_Registration_Request_VIEW_ALL",
    OQF_ER_Registration_Request_VIEW_ALL = "OQF_ER_Registration_Request_VIEW_ALL",

    OQF_ER_REMOVE = "OQF_ER_REMOVE",
    CSEQA_ER_REMOVE = "CSEQA_ER_REMOVE",
    CHEQA_ER_REMOVE = "CHEQA_ER_REMOVE",

    CHEQA_ER_Training_results_Registration_Request_VIEW = "CHEQA_ER_Training_results_Registration_Request_VIEW",
    CHEQA_ER_Training_results_Registration_Request_COMPLETE_TASK = "CHEQA_ER_Training_results_Registration_Request_COMPLETE_TASK",
    CHEQA_ER_Training_results_Registration_Request_CREATE_REQUEST = "CHEQA_ER_Training_results_Registration_Request_CREATE_REQUEST",

    CSEQA_ER_Training_results_Registration_Request_VIEW = "CSEQA_ER_Training_results_Registration_Request_VIEW",
    CHEQA_ER_Training_results_Registration_Request_VIEW_ALL = "CHEQA_ER_Training_results_Registration_Request_VIEW_ALL",
    CSEQA_ER_Training_results_Registration_Request_COMPLETE_TASK = "CSEQA_ER_Training_results_Registration_Request_COMPLETE_TASK",
    CSEQA_ER_Training_results_Registration_Request_CREATE_REQUEST = "CSEQA_ER_Training_results_Registration_Request_CREATE_REQUEST",

    OQF_ER_Training_results_Registration_Request_VIEW = "OQF_ER_Training_results_Registration_Request_VIEW",
    OQF_ER_Training_results_Registration_Request_COMPLETE_TASK = "OQF_ER_Training_results_Registration_Request_COMPLETE_TASK",
    OQF_ER_Training_results_Registration_Request_CREATE_REQUEST = "OQF_ER_Training_results_Registration_Request_CREATE_REQUEST",

    CHEQA_ER_Withdraw_Requests_VIEW_ALL = "CHEQA_ER_Withdraw_Requests_VIEW_ALL",
    CSEQA_ER_Withdraw_Requests_VIEW_ALL = "CSEQA_ER_Withdraw_Requests_VIEW_ALL",
    OQF_ER_Withdraw_Requests_VIEW_ALL = "OQF_ER_Withdraw_Requests_VIEW_ALL",

    CHEQA_External_reviewers_Withdraw_Request_CREATE_REQUEST = "CHEQA_External_reviewers_Withdraw_Request_CREATE_REQUEST",
    CSEQA_External_reviewers_Withdraw_Request_CREATE_REQUEST = "CSEQA_External_reviewers_Withdraw_Request_CREATE_REQUEST",
    OQF_External_reviewers_Withdraw_Request_CREATE_REQUEST = "OQF_External_reviewers_Withdraw_Request_CREATE_REQUEST",

    CHEQA_ER_Withdraw_Request_VIEW = "CHEQA_ER_Withdraw_Request_VIEW",
    CSEQA_ER_Withdraw_Request_VIEW = "CSEQA_ER_Withdraw_Request_VIEW",
    OQF_ER_Withdraw_Request_VIEW = "OQF_ER_Withdraw_Request_VIEW",

    SELF_EVALUATION_DOCUMENT_VIEW = "SELF_EVALUATION_DOCUMENT_VIEW",
    SELF_EVALUATION_DOCUMENT_VIEW_ALL = "SELF_EVALUATION_DOCUMENT_VIEW_ALL",
    SELF_EVALUATION_DOCUMENT_EDIT = "SELF_EVALUATION_DOCUMENT_EDIT",

    CLASSROOM_OBSERVATION_VISIT_FORM_VIEW = "CLASSROOM_OBSERVATION_VISIT_FORM_VIEW",
    CLASSROOM_OBSERVATION_VISIT_FORM_VIEW_ALL = "CLASSROOM_OBSERVATION_VISIT_FORM_VIEW_ALL",
    CLASSROOM_OBSERVATION_VISIT_FORM_CREATE = "CLASSROOM_OBSERVATION_VISIT_FORM_CREATE",
    CLASSROOM_OBSERVATION_VISIT_FORM_REVIEW = "CLASSROOM_OBSERVATION_VISIT_FORM_REVIEW",
    CLASSROOM_OBSERVATION_VISIT_FORM_RETURN_FOR_EDIT = "CLASSROOM_OBSERVATION_VISIT_FORM_RETURN_FOR_EDIT",

    GENERAL_EVIDENCE_VISIT_FORM_VIEW = "GENERAL_EVIDENCE_VISIT_FORM_VIEW",
    GENERAL_EVIDENCE_VISIT_FORM_VIEW_ALL = "GENERAL_EVIDENCE_VISIT_FORM_VIEW_ALL",
    GENERAL_EVIDENCE_VISIT_FORM_CREATE = "GENERAL_EVIDENCE_VISIT_FORM_CREATE",
    GENERAL_EVIDENCE_VISIT_FORM_REVIEW = "GENERAL_EVIDENCE_VISIT_FORM_REVIEW",
    GENERAL_EVIDENCE_VISIT_FORM_RETURN_FOR_EDIT = "GENERAL_EVIDENCE_VISIT_FORM_RETURN_FOR_EDIT",

    VISIT_PLAN_VIEW = "VISIT_PLAN_VIEW",
    SCHOOL_PERFORMANCE = "SCHOOL_PERFORMANCE",
    CSEQA_SCHOOL_PERFORMANCE_SETTING = "CSEQA_SCHOOL_PERFORMANCE_SETTING",
    VISIT_PLAN_VIEW_ALL = "VISIT_PLAN_VIEW_ALL",
    VISIT_PLAN_CREATE = "VISIT_PLAN_CREATE",
    VISIT_PLAN_UPDATE = "VISIT_PLAN_UPDATE",
    VISIT_PLAN_REVIEW = "VISIT_PLAN_REVIEW",

    VISIT_REPORT_CREATE = "VISIT_REPORT_CREATE",
    VISIT_REPORT_VIEW = "VISIT_REPORT_VIEW",
    VISIT_REPORT_VIEW_ALL = "VISIT_REPORT_VIEW_ALL",
    VISIT_REPORT_PROOFREADER = "VISIT_REPORT_PROOFREADER",
    VISIT_REPORT_SCHOOL_VIEW = "VISIT_REPORT_SCHOOL_VIEW",
    VISIT_REPORT_SCHOOL_REVIEW = "VISIT_REPORT_SCHOOL_REVIEW",
    EDIT_SCHOOL_INFO_IN_REPORT = "EDIT_SCHOOL_INFO_IN_REPORT",

    SUMMARY_VISIT_REPORT_CREATE = "SUMMARY_VISIT_REPORT_CREATE",
    SUMMARY_VISIT_REPORT_VIEW = "SUMMARY_VISIT_REPORT_VIEW",
    SUMMARY_VISIT_REPORT_VIEW_ALL = "SUMMARY_VISIT_REPORT_VIEW_ALL",
    SUMMARY_VISIT_REPORT_PROOFREADER = "SUMMARY_VISIT_REPORT_PROOFREADER",
    SUMMARY_VISIT_REPORT_QUALITY_REVIEW = "SUMMARY_VISIT_REPORT_QUALITY_REVIEW",
    SUMMARY_VISIT_REPORT_DELETE = "SUMMARY_VISIT_REPORT_DELETE",
    SUMMARY_VISIT_REPORT_GM_REVIEW = "SUMMARY_VISIT_REPORT_GM_REVIEW",

    DOMAIN_SUMMARY_VIEW = "DOMAIN_SUMMARY_VIEW",

    QA_FOLLOW_UP_FORM_VIEW = "QA_FOLLOW_UP_FORM_VIEW",
    QA_FOLLOW_UP_FORM_COMMENT = "QA_FOLLOW_UP_FORM_COMMENT",
    QA_FOLLOW_UP_FORM_CREATE = "QA_FOLLOW_UP_FORM_CREATE",

    SCHOOL_DOCUMENT_DELIVERY_VIEW = "SCHOOL_DOCUMENT_DELIVERY_VIEW",
    SCHOOL_DOCUMENT_DELIVERY_VIEW_TL = "SCHOOL_DOCUMENT_DELIVERY_VIEW_TL",

    CHEQA_ER_Deletion_Request_CREATE_REQUEST = "CHEQA_ER_Deletion_Request_CREATE_REQUEST",
    CSEQA_ER_Deletion_Request_CREATE_REQUEST = "CSEQA_ER_Deletion_Request_CREATE_REQUEST",
    OQF_ER_Deletion_Request_CREATE_REQUEST = "OQF_ER_Deletion_Request_CREATE_REQUEST",

    CHEQA_ER_Deletion_Request_VIEW_ALL = "CHEQA_ER_Deletion_Request_VIEW_ALL",
    CSEQA_ER_Deletion_Request_VIEW_ALL = "CSEQA_ER_Deletion_Request_VIEW_ALL",
    OQF_ER_Deletion_Request_VIEW_ALL = "OQF_ER_Deletion_Request_VIEW_ALL",

    CSEQA_REPORT_LIST_VIEW = "CSEQA_REPORT_LIST_VIEW",
    OQF_REPORT_LIST_VIEW = "OQF_REPORT_LIST_VIEW",
    CHEQA_REPORT_LIST_VIEW = "CHEQA_REPORT_LIST_VIEW",
    DOMAIN_SUMMARY_VIEW_REPORT = "DOMAIN_SUMMARY_VIEW_REPORT",
    SCHOOL_DOCUMENT_DELIVERY_VIEW_REPORT = "SCHOOL_DOCUMENT_DELIVERY_VIEW_REPORT",
    CLASSROOM_OBSERVATION_VIEW_REPORT = "CLASSROOM_OBSERVATION_VIEW_REPORT",
    GENERAL_EVIDENCE_VIEW_REPORT = "GENERAL_EVIDENCE_VIEW_REPORT",
    CSEQA_OBSERVATION_MONITORING_FORM_VIEW_REPORT = "CSEQA_OBSERVATION_MONITORING_FORM_VIEW_REPORT",
    QA_FOLLOW_UP_FORM_SUBMISSION_VIEW_REPORT = "QA_FOLLOW_UP_FORM_SUBMISSION_VIEW_REPORT",
    VIEW_CSEQA_ER_USERS_REPORT = "VIEW_CSEQA_ER_USERS_REPORT",
    // Admin User Management Permissions
    ADMIN_ADD_USER = "ADMIN_ADD_USER",
    ADMIN_DELETE_USER = "ADMIN_DELETE_USER",
    ADMIN_CHANGE_PASSWORD_FOR_USER = "ADMIN_CHANGE_PASSWORD_FOR_USER",
    ADMIN_GET_ALL_GROUPS = "ADMIN_GET_ALL_GROUPS",
    ADMIN_GET_ALL_ROLES = "ADMIN_GET_ALL_ROLES",
    ADMIN_GET_ALL_PROCEDURES = "ADMIN_GET_ALL_PROCEDURES",
    ADMIN_GET_ALL_USERS = "ADMIN_GET_ALL_USERS",
    ADMIN_VIEW_ROLES = "ADMIN_VIEW_ROLES",
    ADMIN_VIEW_CHANGE_PASSWORD_FOR_USER = "ADMIN_VIEW_CHANGE_PASSWORD_FOR_USER",
    ADMIN_VIEW_USERS = "ADMIN_VIEW_USERS",
    ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER",
    ADMIN_ADD_ROLE = "ADMIN_ADD_ROLE",
    ADMIN_DELETE_ROLE = "ADMIN_DELETE_ROLE",
    ADMIN_UPDATE_ROLE = "ADMIN_UPDATE_ROLE"
}
