export enum VisitSubject {

    ISLAMIC_EDUCATION = 'ISLAMIC_EDUCATION',
    ARABIC_LANGUAGE = 'ARABIC_LANGUAGE',
    ENGLISH_LANGUAGE = 'ENGLISH_LANGUAGE',
    BASIC_MATHEMATICS = 'BASIC_MATHEMATICS',
    ADVANCED_MATHEMATICS = 'ADVANCED_MATHEMATICS',
    GENERAL_MATHEMATICS = 'GENERAL_MATHEMATICS',
    PHYSICS = 'PHYSICS',
    CHEMISTRY = 'CHEMISTRY',
    BIOLOGY = 'BIOLOGY',
    SCIENCE = 'SCIENCE',
    SOCIAL_STUDIES = 'SOCIAL_STUDIES',
    HISTORY = 'HISTORY',
    GEOGRAPHY = 'GEOGRAPHY',
    OTHER = 'OTHER'
}
