export enum VisitDomain {
    ACADEMIC_ACHIEVEMENT = 'ACADEMIC_ACHIEVEMENT',
    PERSONAL_DEVELOPMENT = 'PERSONAL_DEVELOPMENT',
    TEACHING_AND_ASSESSMENT = 'TEACHING_AND_ASSESSMENT',
    LEARNING_ENVIRONMENT = 'LEARNING_ENVIRONMENT',
    LEADERSHIP_AND_GOVERNANCE = 'LEADERSHIP_AND_GOVERNANCE'
}
